name: build

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get Version
      id: version
      run: |
        IMAGE_VERSION=$(curl -s https://api.github.com/repos/rundeck/rundeck/releases/latest | grep 'tag_name' | awk -F ":" '{print $2}' | sed -E 's;"|,|\s|v;;g')
        echo "::set-output name=IMAGE_VERSION::${IMAGE_VERSION}"     

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: | 
          ${{ secrets.DOCKER_HUB_USERNAME }}/rundeck:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/rundeck:${{ steps.version.outputs.IMAGE_VERSION }}